import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import request from "supertest";
import { MongoMemoryServer } from "mongodb-memory-server";
import { createApp } from "../app.js";
import { User, Creator, Service } from "../models/index.js";
import { Notification, Booking, Asset, Message, Project, Reservation } from "../models/marketplace.js";
let db, app, customer, provider, admin, stranger, c, customerUser, providerUser;
const details = { title: "Wedding photography", event: "Wedding", date: "2099-12-20", startTime: "10:00", endTime: "12:00", city: "Kolkata", venue: "Private venue address", instructions: "Warm candid photographs", guestCount: 100 };
before(async () => {
  process.env.JWT_SECRET = "marketplace-test-secret-more-than-32-characters";
  db = await MongoMemoryServer.create(); await mongoose.connect(db.getUri()); app = createApp();
  for (const [name, role] of [["customer", "user"], ["provider", "creator"], ["admin", "admin"], ["stranger", "user"]]) await User.create({ name, email: `${name}@test.example`, role, password: await bcrypt.hash("test-password-123", 4) });
  async function login(name) { const agent = request.agent(app); await agent.post("/api/auth/login").send({ email: `${name}@test.example`, password: "test-password-123" }).expect(200); return agent; }
  customer = await login("customer"); provider = await login("provider"); admin = await login("admin"); stranger = await login("stranger");
  customerUser = await User.findOne({ name: "customer" }); providerUser = await User.findOne({ name: "provider" });
  await Service.create({ title: "Photography", slug: "photography" });
  c = await Creator.create({ user: providerUser._id, businessName: "Test Creative", slug: "test-creative", category: "Photography", services: ["Photography"], location: "Kolkata", city: "Kolkata", availability: [details.date], status: "Active", verified: true, applicationStatus: "APPROVED", email: "private@example.com", phone: "+91 9000012345", socialLinks: { instagram: "https://instagram.com/private" } });
});
after(async () => { await mongoose.disconnect(); await db?.stop(); });
test("public profiles exclude contact details and direct requests remain hidden until admin approval", async () => {
  const profile = (await request(app).get("/api/creators/test-creative").expect(200)).body;
  assert.equal(profile.email, undefined); assert.equal(profile.phone, undefined); assert.equal(profile.socialLinks, undefined);
  const created = await customer.post("/api/bookings").send({ ...details, creator: String(c._id), service: "Photography", amount: 10000 }).expect(201);
  const bid = created.body._id;
  assert.equal(created.body.status, "PENDING_ADMIN_REVIEW"); assert.equal(created.body.commissionAmount, 1500);
  await provider.get(`/api/bookings/${bid}`).expect(404);
  await provider.post(`/api/bookings/${bid}/actions`).send({ action: "accept" }).expect(404);
  assert.equal(await Notification.countDocuments({ user: providerUser._id }), 0);
  await stranger.get(`/api/bookings/${bid}`).expect(404);
  await admin.post(`/api/bookings/${bid}/actions`).send({ action: "approve" }).expect(200);
  assert.equal(await Notification.countDocuments({ user: providerUser._id }), 1);
  const masked = await provider.get(`/api/bookings/${bid}`).expect(200); assert.equal(masked.body.venue, undefined); assert.equal(masked.body.contacts, undefined);
  await provider.post(`/api/bookings/${bid}/actions`).send({ action: "accept" }).expect(200);
  await customer.post(`/api/bookings/${bid}/actions`).send({ action: "paid" }).expect(403);
  await customer.post(`/api/bookings/${bid}/actions`).send({ action: "confirm" }).expect(200);
  await admin.post(`/api/bookings/${bid}/actions`).send({ action: "paid" }).expect(200);
  assert.equal((await Booking.findById(bid)).status, "CONFIRMED"); assert.equal(await Project.countDocuments({ booking: bid }), 1); assert.equal(await Reservation.countDocuments({ booking: bid }), 120);
  const unlocked = await customer.get(`/api/bookings/${bid}`).expect(200); assert.equal(unlocked.body.contacts.creator.email, "private@example.com");
  const asset = await Asset.create({ owner: providerUser._id, purpose: "delivery", contextId: bid, publicId: "test/file", resourceType: "image", originalFilename: "wedding.jpg" });
  const delivery = await provider.post("/api/deliveries").send({ booking: bid, title: "Preview", description: "First delivery", files: [String(asset._id)] }).expect(201);
  await customer.post(`/api/deliveries/${delivery.body._id}/review`).send({ action: "revision", comment: "Please brighten the ceremony photographs." }).expect(200);
  const final = await provider.post("/api/deliveries").send({ booking: bid, title: "Final", description: "Revised photographs", files: [String(asset._id)] }).expect(201);
  await customer.post(`/api/deliveries/${final.body._id}/review`).send({ action: "approve" }).expect(200);
  await customer.post(`/api/bookings/${bid}/actions`).send({ action: "complete" }).expect(200);
  await customer.post("/api/reviews").send({ creator: String(c._id), rating: 5, comment: "A wonderful and thoughtful experience." }).expect(201);
});
test("requirements are gated, proposals ownership is enforced, chat is moderated and acceptance produces a controlled booking", async () => {
  const r = await customer.post("/api/requirements").send({ ...details, startTime: "14:00", endTime: "16:00", services: ["Photography"], budgetMin: 1000, budgetMax: 20000, description: "Please capture candid photographs of the celebration.", deadline: "2099-12-19" }).expect(201);
  const rid = r.body._id;
  await provider.get(`/api/requirements/${rid}`).expect(404);
  assert.equal((await provider.get("/api/requirements?mode=opportunities")).body.length, 0);
  await stranger.put(`/api/requirements/${rid}`).send({ ...details, services: ["Photography"], budgetMin: 1000, budgetMax: 20000, description: "Trying to edit someone else's requirement.", deadline: "2099-12-19" }).expect(404);
  await admin.post(`/api/requirements/${rid}/review`).send({ action: "approve" }).expect(200);
  assert.equal((await provider.get("/api/requirements?mode=opportunities")).body.length, 1);
  const quote = { services: ["Photography"], price: 12000, deliveryDays: 14, message: "We would love to photograph your celebration.", inclusions: "Two hours, one photographer, 100 edited photos", validUntil: "2099-12-19" };
  const p = await provider.post(`/api/requirements/${rid}/proposals`).send(quote).expect(201);
  await stranger.put(`/api/proposals/${p.body._id}`).send(quote).expect(403);
  const conversation = await customer.post("/api/conversations").send({ context: "PROPOSAL", entityId: p.body._id }).expect(200);
  const msg = await customer.post(`/api/conversations/${conversation.body._id}/messages`).send({ text: "Email me at hidden@example.com or +91 9000012345" }).expect(201);
  assert.ok(!msg.body.text.includes("hidden@example.com")); assert.equal(msg.body.original, undefined);
  assert.ok((await Message.findById(msg.body._id).select("+original")).original.includes("hidden@example.com"));
  await stranger.get(`/api/conversations/${conversation.body._id}/messages`).expect(404);
  await customer.post(`/api/proposals/${p.body._id}/actions`).send({ action: "shortlist" }).expect(200);
  const accepted = await customer.post(`/api/proposals/${p.body._id}/actions`).send({ action: "accept" }).expect(200);
  assert.equal((await Booking.findById(accepted.body.booking)).status, "PENDING_ADMIN_REVIEW");
});
test("dynamic forms are admin-managed and required fields are validated by the backend", async () => {
  const body = { key: "photography-proposal", name: "Photography quote", context: "PROPOSAL_FORM", category: "Photography", fields: [{ id: "cameraBrand", label: "Primary camera brand", type: "select", options: ["Canon", "Nikon", "Sony"], optional: false }] };
  await customer.post("/api/admin/configuration/forms").send(body).expect(403);
  const form = await admin.post("/api/admin/configuration/forms").send(body).expect(201);
  const fields = await request(app).get("/api/forms?context=PROPOSAL_FORM&category=Photography").expect(200); assert.equal(fields.body.fields[0].id, "cameraBrand");
  await admin.put(`/api/admin/configuration/forms/${form.body._id}`).send({ ...body, fields: [...body.fields, { id: "team", label: "Team size", type: "number", min: 1, max: 20 }] }).expect(200);
  assert.equal((await admin.get("/api/admin/configuration/forms")).body[0].version, 2);
  await admin.delete(`/api/admin/configuration/forms/${form.body._id}`).expect(200);
  assert.equal((await request(app).get("/api/forms?context=PROPOSAL_FORM&category=Photography")).body.fields.length, 0);
  await admin.post("/api/admin/configuration/forms").send({ key: "requirement-test", name: "Requirement", context: "REQUIREMENT_FORM", fields: [{ id: "style", label: "Preferred style", type: "select", options: ["Candid", "Traditional"] }] }).expect(201);
  const payload = { ...details, services: ["Photography"], budgetMin: 1000, budgetMax: 20000, description: "Please photograph our family celebration.", deadline: "2099-12-19" };
  await customer.post("/api/requirements").send(payload).expect(400);
  await customer.post("/api/requirements").send({ ...payload, answers: { style: "Candid" } }).expect(201);
});
test("confirmed bookings reserve their time and competing confirmations fail without leaking slots", async () => {
  const b = await customer.post("/api/bookings").send({ ...details, creator: String(c._id), service: "Photography", amount: 15000 }).expect(201);
  await admin.post(`/api/bookings/${b.body._id}/actions`).send({ action: "approve" }).expect(200);
  await provider.post(`/api/bookings/${b.body._id}/actions`).send({ action: "accept" }).expect(200);
  await customer.post(`/api/bookings/${b.body._id}/actions`).send({ action: "confirm" }).expect(200);
  await admin.post(`/api/bookings/${b.body._id}/actions`).send({ action: "paid" }).expect(409);
  assert.equal(await Reservation.countDocuments({ booking: b.body._id }), 0);
  assert.equal(await Project.countDocuments({ booking: b.body._id }), 0);
  assert.notEqual((await Booking.findById(b.body._id)).status, "CONFIRMED");
});
test("private verification files, reviews and privileged roles enforce authorization", async () => {
  const a = await Asset.create({ owner: providerUser._id, purpose: "verification", resourceType: "raw", publicId: "private/evidence", originalFilename: "photo.cr3" });
  await customer.get(`/api/assets/${a._id}/access`).expect(403);
  await provider.get(`/api/assets/${a._id}/access`).expect(403);
  await stranger.post("/api/reviews").send({ creator: String(c._id), rating: 5, comment: "A review without a completed booking." }).expect(403);
  await admin.patch(`/api/admin/users/${customerUser._id}`).send({ status: "ACTIVE", role: "super_admin" }).expect(403);
  await customer.get("/api/admin/users").expect(403);
});
test("creator rejection includes a reason and an appeal can be reviewed with an audit trail", async () => {
  await admin.post(`/api/admin/marketplace/applications/${c._id}/review`).send({ action: "reject" }).expect(400);
  await admin.post(`/api/admin/marketplace/applications/${c._id}/review`).send({ action: "reject", reason: "Please supply clearer proof of ownership." }).expect(200);
  await request(app).get(`/api/creators/${c.slug}`).expect(404);
  const appeal = await provider.post("/api/appeals").send({ reason: "Original work evidence", explanation: "I can provide the originals and further evidence of ownership." }).expect(201);
  await customer.post(`/api/appeals/${appeal.body._id}/review`).send({ status: "APPROVED", reason: "This is not permitted." }).expect(403);
  await admin.post(`/api/appeals/${appeal.body._id}/review`).send({ status: "APPROVED", reason: "Additional evidence reviewed and accepted." }).expect(200);
  assert.equal((await Creator.findById(c._id)).applicationStatus, "APPROVED");
  const audits = await admin.get("/api/admin/configuration/audit").expect(200);
  assert.ok(audits.body.some(a => a.action === "CREATOR_REVIEW"));
  assert.ok(audits.body.some(a => a.action === "APPEALS_REVIEW"));
});
test("request drafts are private to their authenticated owner", async () => {
  await customer.put("/api/drafts/requirement").send({ kind: "requirement", values: { title: "Saved wedding plan", venue: "Private draft address" }, step: 3 }).expect(200);
  const draft = await customer.get("/api/drafts/requirement").expect(200);
  assert.equal(draft.body.values.title, "Saved wedding plan"); assert.equal(draft.body.step, 3);
  assert.equal((await stranger.get("/api/drafts/requirement").expect(200)).body, null);
  assert.equal((await provider.get("/api/drafts").expect(200)).body.length, 0);
  await customer.delete("/api/drafts/requirement").expect(200);
  assert.equal((await customer.get("/api/drafts/requirement")).body, null);
});
test("recurring weekly hours support booking and blocked periods take precedence", async () => {
  const date = "2099-12-21", weekday = new Date(`${date}T12:00:00Z`).getUTCDay();
  await provider.put("/api/creator-workspace/availability").send({ availability: [], temporaryLocations: [], weeklyHours: [{ weekday, startTime: "09:00", endTime: "17:00" }], timeSlots: [{ date, startTime: "12:00", endTime: "13:00", blocked: true }] }).expect(200);
  await customer.post("/api/bookings").send({ ...details, date, creator: String(c._id), service: "Photography", amount: 12000, startTime: "10:00", endTime: "11:00" }).expect(201);
  await customer.post("/api/bookings").send({ ...details, date, creator: String(c._id), service: "Photography", amount: 12000, startTime: "12:00", endTime: "13:00" }).expect(409);
});
