const q = (id, label, type = "text", extra = {}) => ({ id, label, type, ...extra });
const camera = [q("cameraAvailable", "Do you have a camera?", "select", { options: ["Yes", "No"] }), q("cameraModel", "Which camera bodies and lenses do you use?", "textarea", { when: { id: "cameraAvailable", value: "Yes" } }), q("backup", "How will you arrange equipment and backup gear?", "textarea"), q("delivery", "What do clients receive, and how soon?", "textarea")];
export const serviceQuestions = {
  "Photography": [...camera, q("style", "Which photography styles and events do you cover?")],
  "Videography": [...camera, q("audio", "Describe your sound, lighting, stabilization and editing setup.", "textarea")],
  "Makeup Artist": [q("specialties", "Which makeup and hair services do you offer?"), q("kit", "Which brands do you use, and how do you sanitize your kit?", "textarea"), q("trial", "Do you offer trials? Describe pricing and travel arrangements.", "textarea")],
  "Mehendi Artist": [q("styles", "Which mehendi styles do you offer?"), q("materials", "What ingredients do you use, and how do you handle sensitivities?", "textarea"), q("capacity", "How many guests can you serve per day?")],
  "Event Decoration": [q("themes", "Which event types and decoration themes do you offer?"), q("inventory", "Describe your decor inventory and what clients must arrange.", "textarea"), q("setup", "How much time and venue access do setup and removal need?", "textarea")],
  "Camera Rental": [q("inventory", "List camera models, lenses, accessories and quantities.", "textarea"), q("deposit", "What deposit, renter ID and damage policy do you require?", "textarea"), q("handover", "Explain pickup, delivery, return and late-fee arrangements.", "textarea")],
  "Studio Rental": [q("space", "Describe studio size, guest capacity and available sets.", "textarea"), q("equipment", "What lighting, equipment and amenities are included?", "textarea"), q("rules", "What are your hours, minimum booking and studio rules?", "textarea")],
  "Wedding Planner": [q("scope", "Do you offer full planning, partial planning or day-of coordination?"), q("capacity", "What guest counts and event budgets do you support?"), q("vendors", "Describe your team, vendor coordination and contingency arrangements.", "textarea")],
};
export function questions(kind, service) {
  if (kind === "user") return [q("city", "Which city do you live in?"), q("interests", "Which services interest you?", "multiselect"), q("occasion", "What are you planning?", "select", { options: ["Wedding", "Family celebration", "Creative project", "Business event", "Just exploring"] })];
  return [q("service", "Which service would you like to provide?", "service"), q("businessName", "What is your business or professional name?"), q("phone", "What phone number can our team contact?", "tel"), q("bio", "Tell clients about yourself and your work.", "textarea", { minLength: 20 }), q("experience", "How many years of professional experience do you have?", "number", { max: 80 }), q("perDayRate", "What is your starting rate per day (INR)?", "number", { min: 1, max: 10000000 }), q("inclusions", "What does that rate include? Mention hours, extras and travel charges.", "textarea"), ...(serviceQuestions[service] || [q("specialties", "Describe your specialties, equipment and service process.", "textarea")]), q("city", "Which city are you based in?"), q("state", "Which state are you based in?"), q("address", "What is your full business address, including postal code?", "textarea", { help: "Only the review team sees your detailed address." }), q("servingArea", "Which cities or areas will you serve?"), q("travel", "Are you available for travel?", "select", { options: ["Local only", "Within my state", "Across India", "International"] }), q("notice", "How far ahead should clients book, and what is your usual availability?", "textarea"), q("policy", "Describe your advance payment, cancellation and rescheduling policy.", "textarea"), q("profileImage", "Upload your profile or business image.", "image"), q("workSamples", "Upload 1–6 images of your work or rental inventory.", "images"), q("portfolio", "Portfolio or video link (optional)", "url", { optional: true }), q("idType", "Which valid ID will you provide?", "select", { options: ["Passport", "Driving licence", "Voter ID", "Other government-issued ID"] }), q("idCard", "Upload a clear image of your valid ID.", "image", { help: "Private verification document. Visible only to the review team; never added to your portfolio." }), q("consent", "I confirm these details are accurate and authorize Memooria to review my application and ID.", "checkbox")];
}
